# Generated by Django 4.1.5 on 2023-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('word_id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('translate', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('ban_word', models.BooleanField(default=False)),
            ],
        ),
    ]
